### PR TITLE
Updated NativeWebSocket to 1.1.3

### PR DESCRIPTION
**Pull request by KoenRijpstra**
The following bugs are fixed in the latest NativeWebSocket 1.1.3:

- Nintendo Switch support (https://github.com/colyseus/colyseus-unity3d/pull/182)
- Fixes WebGL build on Unity 2021.2 (https://github.com/endel/NativeWebSocket/pull/54)
- Remove unnecessary memory allocations when receiving messages (https://github.com/endel/NativeWebSocket/pull/40)

More info here: https://github.com/endel/NativeWebSocket/releases/tag/1.1.3

Fixes issue: https://github.com/ethereum-boilerplate/ethereum-unity-boilerplate/issues/48

### CODE REVIEW

**Review by xactant — COMMENTED** [review]
Need to review with you as this is a Wallet Connect  file.

**Comment by xactant** [comment]
Also have these changes been tested with 2020.3.26 & 2020.3.30?

**Comment by xactant** [comment]
These changes are in Wallet Connect so Koen is going to send the PR to Wallet Connect.

These changes need to be tested with the 2020.3.n versions to make sure these changes do not break older Unity version.

**Comment by KoenRijpstra** [comment]
I made the PR for Wallet Connect: https://github.com/WalletConnect/WalletConnectUnity/pull/36

And tested it with Unity 2019.4.36f1 and 2020.3.29f

**Comment by KoenRijpstra** [comment]
@xactant Good news the PR is merged: https://github.com/WalletConnect/WalletConnectUnity/pull/36#event-6186923199

**Comment by KoenRijpstra** [comment]
NativeWebSocket already updated in Moralis / Unity3D Asset Package v1.1.0. 🥳  Closing PR.

**Pull request closed without merging**
